version: '3'
services:

  app:
    image: golang:1.10rc1-stretch
    container_name: app
    command: bash -c "cd /app-telegram; ./app-telegram"
    links:
      - mongo
    volumes:
      - ./app-telegram:/app-telegram/app-telegram
      - ./.env:/app-telegram/.env

  mongo:
    container_name: db
    ports:
      - 27017:27017
    image: mongo:3.5.13
    volumes:
      - ./etc/mongo:/data/db
